---
- name: Clonando MVs. Ovejas para hadoop
  hosts: localhost
  gather_facts: false
  vars_files:
    - varOvejas.yml

  tasks:
    - name: Login to IaaS
      ovirt_auth:
        url: https://iaas.ull.es/ovirt-engine/api
        insecure: yes
        username: alu0101371030@ULL
        password: "{{ ovirt_password }}"
        headers:
          filter: true

    - name: Create a VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: Cluster-Rojo
        name: "DevOps-Grupo3-{{ item.name }}"
        template: Centos-7
        nics: "{{ node_nics }}"
        state: present
        wait: yes
      with_items: "{{ nodes }}"
    
    - name: Update VM via cloud-init
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "DevOps-Grupo3-{{ item.name }}"
        state: running
        cloud_init_nics:
          - nic_name: eth0
            nic_boot_protocol: dhcp
            nic_on_boot: true
          - nic_name: eth1
            nic_boot_protocol: dhcp
            nic_on_boot: true
          - nic_name: eth2
            nic_boot_protocol: dhcp
            nic_on_boot: true
        cloud_init:
          host_name: "{{ item.name }}"
          user_name: ansible
          root_password: $6$mTZ2ohs1$DuhB0YbPPfqyBEThGTZG193sGVJHandpT4260DqdxnfK.G4Wuq/Mx9bRq5nJAQFJzcXiDVpuTtbdz1cJd5lXu.
          authorized_ssh_keys: "{{ ssh_keys }}"
          custom_script: |
            write_files:
              - path: /etc/sudoers.d/ansible
                permissions: '0644'
                content: |
                  ansible ALL=(ALL) NOPASSWD:ALL
            runcmd:
              - sed -i '/AllowUsers/c\AllowUsers adminstic usuario soporteiass ansible hadoop' /etc/ssh/sshd_config
              - systemctl restart sshd
        wait: yes
      with_items: "{{ nodes }}"

    - name: Cleanup IaaS auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
