- name: Install NGINX
  hosts: loadbalancer
  roles:
    - common
    - nginx

- name: Adjust SELinux
  hosts: loadbalancer
  tasks:
    - name: Run command
      command: setsebool -P httpd_can_network_connect 1
